# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b00a9ef8e9bb018cdfcd163c6bb69ccc9659db133882be9e961bd77e446e4957d21569331ae06c7ac61e5da7f6518ee28b8736b7d1469e7e3a1ffd240e7a245

test:
  secret_key_base: 6782493f58633730b77b844e7b625a70cecf622ca9676eb183f24fe3a868a588d2fd40e3f9d9ef98cac1734e054fd98e5480c5cbcf9f3affe965cb7f47968183

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
